### ISSUE TITLE
Why provide useCallbackOne?

### ISSUE THREAD

**Issue by rimunroe** [alexreardon/use-memo-one#8]
`useMemoOne` is really handy! Thanks for making it! I just have a few questions about `useCallbackOne`: The React hooks API docs quoted in the readme specifically explain that `useMemo` should not be relied on for semantic guarantee, but I don't see anything like that for `useCallback`. Do you have additional info regarding this?

Also, since `useMemoOne` is intended to be used to create arbitrary values which are stable across re-renders, why provide `useCallbackOne` at all?

**Comment by denis-sokolov** [comment]
Indeed, useCallback has the same behavior as useMemo, see [the React issue](https://github.com/facebook/react/issues/15278).

**Comment by rimunroe** [comment]
Ah! You're right. I'll go ahead and close this then.
